services:
  - type: web
    name: portafolio-alexis
    runtime: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install && npm run build
      php artisan optimize
    startCommand: |
      touch database/database.sqlite
      php artisan migrate --force
      # Inicia el servidor y el cron interno en segundo plano
      (while true; do php artisan schedule:run; sleep 600; done) & 
      apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite